import { AppSidebar } from "@/components/Sidebar/AppSidebar";
import SidebarStateClient from "@/components/Sidebar/SidebarTriggerStateClient";
import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../styles/globals.css";

export const font = Montserrat({
  weight: ["400", "500", "600", "700"],
  display: "swap",
  fallback: ["Helvetica", "Arial", "sans-serif"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${font.className} font-sans antialiased`}>
        <SidebarProvider>
          <AppSidebar />
            <SidebarStateClient />
          <main>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
